# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_status',
            field=models.CharField(choices=[('a', 'Доступно'), ('na', 'Не доступно')], max_length=2),
        ),
        migrations.AlterField(
            model_name='orders',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Items', verbose_name='Желаемая книга'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_adress',
            field=models.CharField(default='None', max_length=100, verbose_name='Желаемый адрес доставки'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_comment',
            field=models.TextField(blank=True, max_length=512, verbose_name='Ваш комментарий (пожелания, номер телефона для связи, т.д.)'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('p', 'Комплектуется'), ('d', 'Отправляется'), ('f', 'Отправлено'), ('c', 'Отменено')], max_length=2, verbose_name='Статус заказа'),
        ),
    ]
