# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161128_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_description',
            field=models.TextField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('p', 'Packing'), ('d', 'Delivering'), ('f', 'Delivered'), ('c', 'Cancelled')], max_length=2),
        ),
    ]
