# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_item_orders_items_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='loginname',
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='firstname',
            field=models.CharField(default='Tom', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='lastname',
            field=models.CharField(default='Smith', max_length=512),
            preserve_default=False,
        ),
    ]
