# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161113_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='loginname',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
