# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161117_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='items',
            name='item_tags',
        ),
        migrations.AddField(
            model_name='items',
            name='item_tags',
            field=models.ManyToManyField(related_name='p', to='blog.Tags'),
        ),
    ]
