# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20161113_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='loginname',
            new_name='login',
        ),
        migrations.AddField(
            model_name='itemorders',
            name='item_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='blog.Items'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemorders',
            name='order_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='blog.Orders'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='author_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='blog.Authors'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='item_status',
            field=models.CharField(default='Avialable', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='item_tags',
            field=models.CharField(default='none', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='release_date',
            field=models.DateField(default='2016-12-12'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_date',
            field=models.DateField(default='2016-12-12'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_status',
            field=models.CharField(default='Delivered', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='total_price',
            field=models.IntegerField(default='100'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='blog.Users'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='item_price',
            field=models.IntegerField(default='100'),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
