# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20161114_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemStatusList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_status', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='items',
            name='item_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ItemStatusList', to_field='item_status'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.OrderStatusList', to_field='order_status'),
        ),
    ]
