# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20161115_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(auto_now=True)),
                ('comment_text', models.TextField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='item_rating',
            field=models.DecimalField(decimal_places=1, default='5.0', max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Items'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Users'),
        ),
    ]
