# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20161115_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_status',
            field=models.CharField(choices=[('a', 'Avialable'), ('na', 'Not Avialable')], max_length=2),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('p', 'Packing'), ('d', 'Delivering'), ('dd', 'Delivered')], max_length=2),
        ),
        migrations.DeleteModel(
            name='OrderStatusList',
        ),
    ]
