# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20161115_1923'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemStatusList',
        ),
    ]
