# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_delete_itemstatuslist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='cv/')),
                ('age', models.IntegerField(default=0)),
                ('is_married', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='order_adress',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_comment',
            field=models.TextField(blank=True, max_length=512),
        ),
    ]
