# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20161115_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='item_count',
            field=models.ManyToManyField(related_name='p', to='blog.Items'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.Users'),
        ),
    ]
