# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20161115_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemorders',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='itemorders',
            name='order_id',
        ),
        migrations.DeleteModel(
            name='ItemOrders',
        ),
    ]
